// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Panel2;
lv_obj_t * ui_Panel3;
lv_obj_t * ui_Panel5;
lv_obj_t * ui_Panel6;
lv_obj_t * ui_LabeId1;
lv_obj_t * ui_LabeId2;
lv_obj_t * ui_LabeId3;
lv_obj_t * ui_LabeId4;
lv_obj_t * ui_LabeId5;
lv_obj_t * ui_LabeId6;
lv_obj_t * ui_LabelSensor1;
lv_obj_t * ui_LabelSensor2;
lv_obj_t * ui_LabelSensor3;
lv_obj_t * ui_LabelSensor4;
lv_obj_t * ui_LabelSensor5;
lv_obj_t * ui_LabelSensor6;

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
lv_obj_t * ui_Screen2;
void ui_event_Panel7(lv_event_t * e);
lv_obj_t * ui_Panel7;
lv_obj_t * ui_DropdownSF;
lv_obj_t * ui_DropdownBW;
lv_obj_t * ui_DropdownPower;
lv_obj_t * ui_DropdownCrc;
lv_obj_t * ui_Button1;
void ui_event_TextArea1(lv_event_t * e);
lv_obj_t * ui_TextArea1;
lv_obj_t * ui_Label1;
lv_obj_t * ui_Label2;
lv_obj_t * ui_Label3;
lv_obj_t * ui_Label4;
lv_obj_t * ui_Label5;
lv_obj_t * ui_Label6;
lv_obj_t * ui_Keyboard1;
lv_obj_t * ui____initial_actions0;

void ui_event_button1(lv_event_t * e);

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_MOVE_LEFT, 300, 0, &ui_Screen2_screen_init);
    }
}
void ui_event_Screen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 300, 0, &ui_Screen1_screen_init);
    }
}
void ui_event_Panel7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}
void ui_event_TextArea1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_TextArea1);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

#include "LoraBoard.h"
#include <stdio.h>
#include <FreeRTOS.h>
#include <task.h>
#include <event_groups.h>
#include <queue.h>

extern TaskHandle_t LoraBoard_task_hd;

void ui_event_button1(lv_event_t * e)
{
    char *p_text;
    char buf[20];
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_CLICKED) {
        p_text = lv_textarea_get_text(ui_TextArea1);
        lora_settings.lora_freq = atoi(p_text);
        // p_text = lv_dropdown_get_options(ui_DropdownSF);
        memset(buf, 0, 20);
        lv_dropdown_get_selected_str(ui_DropdownSF, buf, 20);
        lora_settings.lora_sf = atoi(buf);
        // p_text = lv_dropdown_get_options(ui_DropdownBW);
        memset(buf, 0, 20);
        lv_dropdown_get_selected_str(ui_DropdownBW, buf, 20);
        lora_settings.lora_bw = atoi(buf);
        // p_text = lv_dropdown_get_options(ui_DropdownPower);
        memset(buf, 0, 20);
        lv_dropdown_get_selected_str(ui_DropdownPower, buf, 20);
        lora_settings.lora_power = atoi(buf);
        // p_text = lv_dropdown_get_options(ui_DropdownCrc);
        memset(buf, 0, 20);
        lv_dropdown_get_selected_str(ui_DropdownCrc, buf, 20);
        lora_settings.lora_crc = atoi(buf);
        xTaskNotifyIndexed(LoraBoard_task_hd, UART_ISR_NOTIFY_INDEX, 2, eSetValueWithOverwrite);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
    
}
