// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Panel3;
extern lv_obj_t * ui_Panel5;
extern lv_obj_t * ui_Panel6;
extern lv_obj_t * ui_LabeId1;
extern lv_obj_t * ui_LabeId2;
extern lv_obj_t * ui_LabeId3;
extern lv_obj_t * ui_LabeId4;
extern lv_obj_t * ui_LabeId5;
extern lv_obj_t * ui_LabeId6;
extern lv_obj_t * ui_LabelSensor1;
extern lv_obj_t * ui_LabelSensor2;
extern lv_obj_t * ui_LabelSensor3;
extern lv_obj_t * ui_LabelSensor4;
extern lv_obj_t * ui_LabelSensor5;
extern lv_obj_t * ui_LabelSensor6;
// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
void ui_event_Panel7(lv_event_t * e);
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_DropdownSF;
extern lv_obj_t * ui_DropdownBW;
extern lv_obj_t * ui_DropdownPower;
extern lv_obj_t * ui_DropdownCrc;
extern lv_obj_t * ui_Button1;
void ui_event_TextArea1(lv_event_t * e);
extern lv_obj_t * ui_TextArea1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Keyboard1;
extern lv_obj_t * ui____initial_actions0;

void ui_event_button1(lv_event_t * e);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
