// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.1
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 97);
    lv_obj_set_height(ui_Panel1, 77);
    lv_obj_set_x(ui_Panel1, -105);
    lv_obj_set_y(ui_Panel1, -42);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel4, 98);
    lv_obj_set_height(ui_Panel4, 78);
    lv_obj_set_x(ui_Panel4, -104);
    lv_obj_set_y(ui_Panel4, 40);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 97);
    lv_obj_set_height(ui_Panel2, 77);
    lv_obj_set_x(ui_Panel2, 103);
    lv_obj_set_y(ui_Panel2, -41);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel3 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel3, 97);
    lv_obj_set_height(ui_Panel3, 77);
    lv_obj_set_x(ui_Panel3, -2);
    lv_obj_set_y(ui_Panel3, -41);
    lv_obj_set_align(ui_Panel3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel5 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel5, 98);
    lv_obj_set_height(ui_Panel5, 78);
    lv_obj_set_x(ui_Panel5, 103);
    lv_obj_set_y(ui_Panel5, 39);
    lv_obj_set_align(ui_Panel5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel5, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel6 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel6, 98);
    lv_obj_set_height(ui_Panel6, 78);
    lv_obj_set_x(ui_Panel6, 0);
    lv_obj_set_y(ui_Panel6, 39);
    lv_obj_set_align(ui_Panel6, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel6, lv_color_hex(0x1E1B1B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId1, -107);
    lv_obj_set_y(ui_LabeId1, -68);
    lv_obj_set_align(ui_LabeId1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId1, "id:1");
    lv_obj_set_style_text_color(ui_LabeId1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId2, 0);
    lv_obj_set_y(ui_LabeId2, -68);
    lv_obj_set_align(ui_LabeId2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId2, "id:1");
    lv_obj_set_style_text_color(ui_LabeId2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId3, 105);
    lv_obj_set_y(ui_LabeId3, -68);
    lv_obj_set_align(ui_LabeId3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId3, "id:1");
    lv_obj_set_style_text_color(ui_LabeId3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId4, -108);
    lv_obj_set_y(ui_LabeId4, 10);
    lv_obj_set_align(ui_LabeId4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId4, "id:1");
    lv_obj_set_style_text_color(ui_LabeId4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId5, -2);
    lv_obj_set_y(ui_LabeId5, 9);
    lv_obj_set_align(ui_LabeId5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId5, "id:1");
    lv_obj_set_style_text_color(ui_LabeId5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabeId6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabeId6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabeId6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabeId6, 106);
    lv_obj_set_y(ui_LabeId6, 10);
    lv_obj_set_align(ui_LabeId6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabeId6, "id:1");
    lv_obj_set_style_text_color(ui_LabeId6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabeId6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabeId6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor1, -130);
    lv_obj_set_y(ui_LabelSensor1, -41);
    lv_obj_set_align(ui_LabelSensor1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor1, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor1, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor1, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor2, -27);
    lv_obj_set_y(ui_LabelSensor2, -41);
    lv_obj_set_align(ui_LabelSensor2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor2, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor2, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor2, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor3 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor3, 80);
    lv_obj_set_y(ui_LabelSensor3, -40);
    lv_obj_set_align(ui_LabelSensor3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor3, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor3, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor3, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor4 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor4, -131);
    lv_obj_set_y(ui_LabelSensor4, 36);
    lv_obj_set_align(ui_LabelSensor4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor4, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor4, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor4, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor5 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor5, -25);
    lv_obj_set_y(ui_LabelSensor5, 34);
    lv_obj_set_align(ui_LabelSensor5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor5, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor5, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor5, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelSensor6 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelSensor6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelSensor6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSensor6, 79);
    lv_obj_set_y(ui_LabelSensor6, 35);
    lv_obj_set_align(ui_LabelSensor6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelSensor6, "temp:\nhumi:\nPH:");
    lv_obj_set_style_text_color(ui_LabelSensor6, lv_color_hex(0xBDFFEF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelSensor6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelSensor6, LV_TEXT_ALIGN_AUTO, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelSensor6, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Screen1, ui_event_Screen1, LV_EVENT_ALL, NULL);

}
